# Generated by rust2rpm 13
%bcond_without check
%global __cargo_skip_build 0

%global crate silver

Name:           rust-%{crate}
Version:        1.1.0
Release:        3%{?dist}
Summary:        Cross-shell customizable powerline-like prompt with icons

# Upstream license specification: Unlicense
License:        Unlicense
URL:            https://crates.io/crates/silver
Source:         %{crates_source}
# Initial patched metadata
# * No Windows
# * Bump git2 to 0.11 https://github.com/reujab/silver/pull/22
Patch0:         silver-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Cross-shell customizable powerline-like prompt with icons.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license unlicense
%doc readme.md
%{_bindir}/silver

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install
rm -f %{buildroot}%{_prefix}/.crates2.json

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Feb 02 20:23:45 CET 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.1.0-3
- Bump git2 to 0.11

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.1.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Sep 12 08:25:53 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.1.0-1
- Update to 1.1.0

* Sun Sep 01 20:42:10 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.8-1
- Update to 1.0.8

* Sun Jul 28 15:47:34 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.7-4
- Regenerate

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.7-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Fri Jun 07 2019 Josh Stone <jistone@redhat.com> - 1.0.7-2
- Bump git2 to 0.9

* Thu May 09 2019 Josh Stone <jistone@redhat.com> - 1.0.7-1
- Update to 1.0.7

* Fri Apr 26 20:18:32 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 1.0.5-1
- Initial package
